from django.contrib import admin
from django.urls import path, include
from . import views 
urlpatterns = [
    path('pro', views.index, name='index'),
    path('assets/<int:id>/', views.asset_details, name='asset_details'),
    path('assets/<int:id>/post', views.post, name='post'),
    path('', views.home, name='home'),
    path('calendar', views.calendar, name='calendar'),
    path('explore', views.explore, name='explore'),
    path('messages', views.messages, name='messages'),
    path('conversation/<int:conversation_id>/', views.conversation, name='conversation'),
    path('conversation/<int:conversation_id>/send-message', views.send_message, name='send_message'),
    path('news', views.news, name='news'),
    path('polls', views.polls, name='polls'), 
    path('search_polls_assets', views.search_polls_assets, name='search_polls_assets'),
    path('update_poll/<int:asset_id>/<str:poll_type>', views.update_poll, name='update_poll'),
    path('signals', views.signals, name='signals'), 
    path('update_vote/<int:signal_id>/<str:vote_type>', views.update_vote, name='update_vote'),
    path('get_signal_details/<int:signal_id>', views.get_signal_details, name='get_signal_details'),
    path('blog', views.blog, name='blog'),
    path('communities', views.communities, name='communities'),
    path('community/<int:community_id>/', views.view_community, name='view_community'),
    path('community/<int:community_id>/join_community', views.join_community, name='join_community'),
    path('community/<int:community_id>/leave_community', views.leave_community, name='leave_community'),
    path('community/<int:community_id>/delete_community', views.delete_community, name='delete_community'),
    path('community/<int:community_id>/send_community_message', views.send_community_message, name='send_community_message'),
    path('notification', views.notifications, name='notifications'),
    path('my_profile', views.profile, name='profile'),
    path('forex_assets', views.forex_assets, name='forex_assets'),
    path('crypto_assets', views.crypto_assets, name='crypto_assets'),
    path('stocks_assets', views.stocks_assets, name='stocks_assets'),
    path('nft_assets', views.nft_assets, name='nft_assets'),
    path('commodities_assets', views.commodities_assets, name='commodities_assets'),
    path('indices_assets', views.indices_assets, name='indices_assets'),
    path('bonds_assets', views.bonds_assets, name='bonds_assets'),
    path('etfs_assets', views.etfs_assets, name='etfs_assets'),
    path('reits_assets', views.reits_assets, name='reits_assets'),
    path('other_assets', views.other_assets, name='other_assets'),
    path('about_us', views.company, name='company'),
    path('learn', views.learn, name='learn'),
    path('smartbat', views.smartbat, name='smartbat'),
    path('login', views.login, name='login'),
    path('sign_out', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('create_signal', views.create_signal, name='create_signal'),
    path('create_community', views.create_community, name='create_community'),
    path('postfeed', views.postfeed, name='postfeed'),
    path('save_profile', views.save_profile, name='save_profile'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('comment/<int:post_id>/', views.comment, name='comment'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    
    path('follow_profile/<int:profile_id>/', views.follow_profile, name='follow_profile'),
]
